// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.shekhar.roo.conference.domain;

import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Conference_Roo_Configurable {
    
    declare @type: Conference: @Configurable;
    
}
