// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.shekhar.playground.roo.wedding.domain;

import com.shekhar.playground.roo.wedding.domain.Rsvp;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect RsvpDataOnDemand_Roo_DataOnDemand {
    
    declare @type: RsvpDataOnDemand: @Component;
    
    private Random RsvpDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Rsvp> RsvpDataOnDemand.data;
    
    public Rsvp RsvpDataOnDemand.getNewTransientRsvp(int index) {
        com.shekhar.playground.roo.wedding.domain.Rsvp obj = new com.shekhar.playground.roo.wedding.domain.Rsvp();
        obj.setAttending(new Integer(index));
        java.lang.String code = "code_" + index;
        if (code.length() > 30) {
            code  = code.substring(0, 30);
        }
        obj.setCode(code);
        obj.setConfirmed(new java.util.Date());
        obj.setEmail("email_" + index);
        java.lang.String specialRequests = "specialRequests_" + index;
        if (specialRequests.length() > 100) {
            specialRequests  = specialRequests.substring(0, 100);
        }
        obj.setSpecialRequests(specialRequests);
        return obj;
    }
    
    public Rsvp RsvpDataOnDemand.getSpecificRsvp(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Rsvp obj = data.get(index);
        return Rsvp.findRsvp(obj.getId());
    }
    
    public Rsvp RsvpDataOnDemand.getRandomRsvp() {
        init();
        Rsvp obj = data.get(rnd.nextInt(data.size()));
        return Rsvp.findRsvp(obj.getId());
    }
    
    public boolean RsvpDataOnDemand.modifyRsvp(Rsvp obj) {
        return false;
    }
    
    public void RsvpDataOnDemand.init() {
        data = com.shekhar.playground.roo.wedding.domain.Rsvp.findRsvpEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Rsvp' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<com.shekhar.playground.roo.wedding.domain.Rsvp>();
        for (int i = 0; i < 10; i++) {
            com.shekhar.playground.roo.wedding.domain.Rsvp obj = getNewTransientRsvp(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
