// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.shekhar.roo.conference.domain;

import com.shekhar.roo.conference.domain.ConferenceDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ConferenceIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ConferenceIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ConferenceIntegrationTest: @Transactional;
    
    @Autowired
    private ConferenceDataOnDemand ConferenceIntegrationTest.dod;
    
    @Test
    public void ConferenceIntegrationTest.testCountConferences() {
        org.junit.Assert.assertNotNull("Data on demand for 'Conference' failed to initialize correctly", dod.getRandomConference());
        long count = com.shekhar.roo.conference.domain.Conference.countConferences();
        org.junit.Assert.assertTrue("Counter for 'Conference' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ConferenceIntegrationTest.testFindConference() {
        com.shekhar.roo.conference.domain.Conference obj = dod.getRandomConference();
        org.junit.Assert.assertNotNull("Data on demand for 'Conference' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Conference' failed to provide an identifier", id);
        obj = com.shekhar.roo.conference.domain.Conference.findConference(id);
        org.junit.Assert.assertNotNull("Find method for 'Conference' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Conference' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ConferenceIntegrationTest.testFindAllConferences() {
        org.junit.Assert.assertNotNull("Data on demand for 'Conference' failed to initialize correctly", dod.getRandomConference());
        long count = com.shekhar.roo.conference.domain.Conference.countConferences();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Conference', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.shekhar.roo.conference.domain.Conference> result = com.shekhar.roo.conference.domain.Conference.findAllConferences();
        org.junit.Assert.assertNotNull("Find all method for 'Conference' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Conference' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ConferenceIntegrationTest.testFindConferenceEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Conference' failed to initialize correctly", dod.getRandomConference());
        long count = com.shekhar.roo.conference.domain.Conference.countConferences();
        if (count > 20) count = 20;
        java.util.List<com.shekhar.roo.conference.domain.Conference> result = com.shekhar.roo.conference.domain.Conference.findConferenceEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Conference' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Conference' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ConferenceIntegrationTest.testFlush() {
        com.shekhar.roo.conference.domain.Conference obj = dod.getRandomConference();
        org.junit.Assert.assertNotNull("Data on demand for 'Conference' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Conference' failed to provide an identifier", id);
        obj = com.shekhar.roo.conference.domain.Conference.findConference(id);
        org.junit.Assert.assertNotNull("Find method for 'Conference' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyConference(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Conference' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ConferenceIntegrationTest.testMerge() {
        com.shekhar.roo.conference.domain.Conference obj = dod.getRandomConference();
        org.junit.Assert.assertNotNull("Data on demand for 'Conference' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Conference' failed to provide an identifier", id);
        obj = com.shekhar.roo.conference.domain.Conference.findConference(id);
        boolean modified =  dod.modifyConference(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.shekhar.roo.conference.domain.Conference merged = (com.shekhar.roo.conference.domain.Conference) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Conference' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ConferenceIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Conference' failed to initialize correctly", dod.getRandomConference());
        com.shekhar.roo.conference.domain.Conference obj = dod.getNewTransientConference(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Conference' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Conference' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Conference' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ConferenceIntegrationTest.testRemove() {
        com.shekhar.roo.conference.domain.Conference obj = dod.getRandomConference();
        org.junit.Assert.assertNotNull("Data on demand for 'Conference' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Conference' failed to provide an identifier", id);
        obj = com.shekhar.roo.conference.domain.Conference.findConference(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Conference' with identifier '" + id + "'", com.shekhar.roo.conference.domain.Conference.findConference(id));
    }
    
}
